DROP TABLE warehouse_staff;
DROP TABLE agent;
DROP TABLE client;
DROP TABLE supplier;
DROP TABLE itemtypes;
DROP TABLE item;
DROP TABLE invoice;
DROP TABLE delivery_content;
DROP TABLE issuance_content;
DROP TABLE user_account;

DROP TABLE discountrates;
DROP TABLE delivery;
DROP TABLE item_issuance;
DROP TABLE invoice_content;
DROP TABLE item_transfer;
DROP TABLE item_return;
DROP TABLE transfer_content;
DROP TABLE return_content;
